travis:
  secure:
    BINSTAR_TOKEN: JoPCOoX7Tq8YfAOHSmg2yMqSBrx1K/U1/+lsXxMPDFNCPQfq5vy+opJ5hGMQBSvBC9a4mR7SU/kurdUMmf2Tgpn4ftV1rgbTlTb55LNcR18Cs7Ivys9owH2b25TEAYn2TcQ8hiZWeyhQyzr4Ks7QruwgKUy7DLhPtBOzpgD1w3PLI9RKIQ2i4Ke/Ez7bV05X/s/ihBYG7E1uLWE8PHTumbZCkiQxZbfaAUP4gQR96rwQRZp7ovJEtNwBHk2QOAYotZXu+9DyujyYwoH+r9HT8BEwekUCctgwWFuJszU16b/bzH5bC16ZCdZpM1/zTTa31JlhtjuWbqlir2npZc5iXWPdyGaXvj16utKtJcjteYebnuMGto8exI9GzuXinUHaL9662ElcUtRhvy9VuwZeyA6AqRZaQRuDQs6fD1FYX4q9kQfPR3OC2BP64WvR3C2iThsyydtGt31FVlzTeOnG7X6RbO840eF836GZzOqCQfBJaZjYNaMzqe7yV8ryVXrtt8Gr9ewtqz+IEZzEPS3e42MYsKFlELMuV/1piFtYwaREIn7qTT1iG6s2uLX1ywT6AQlsQ0S4VHZZ8rGAui3aIAgzgtfbY66PfVwtbqS+iHc81kWOQb619iUJdTvocWy08tRVdHjl4rMzcvuBIFHBLZhHrBHXwu0GcTgdAEtzBsM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
