travis:
  secure:
    BINSTAR_TOKEN: PiT5tMWNF4HCOYiJWQAH6NReIzyLmPi8IdLdKjMWE3evGaqRxVbOxWTMotR5KCnPWLwUG3zaJHSSIOH0gBzW3/Jx6gKgiskjzTqoZD+3Slw/TrB+LM8iSdd0z6w28H0NFkw+Sp+ahISBkHOJHNF8Tgj/Uj5oidEPqGqyVD5/qu95+1fRkdG4Dk/ipQ57WgAVCeuBQPbqj22/r87rd3wTePKsJR3xDyvxnz5+DxzwtzWhNSIc0v8LDlej/ISqi1TEocmFmSlPKtluKvsjmuIXdZ1y7JvtdvOE0idz7+wYpXGC4gmYMClc96aQeWS7XzxfNbhvVllK/iklAUHoijU9cywvUs3lPCMgmBFJ1wTAhbaQaja0RFKIFSGA578hDtF6vgcwK9k/ROW4FbsO6T23vHER/LVblezA38Zt7hAw7nJHc1wzv64+IW6GmXn3CCLP96BvkEBjlESaccdrlVhk6WhRfyqM/KzZzaxCLxuH0Xfpyai+tRAgNdXpZJys9/Rm3fV9dvsARQ0vKsfCQFH46XKazr8K9JhBCifnXVlUBgxZT4vYrkVRoNU/AqtNhtno8cZ8auoUDBkSRWtF3ycfYucQCK/KqTxD1iCeS8GEfwykxi2hcwsfbPbZvhRMWUX56eD7K3qX/Yo/sLePxzPVT++LPHCCXRlXY4z+ivCimqo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
